apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: stuck-demo
spec:
  schema:
    group: kro.run
    apiVersion: v1alpha1
    kind: StuckDemo

    spec:
      name: string

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
              - name: app
                image: does-not-exist.invalid/nginx:latest

      readyWhen:
        - ${deployment.status.availableReplicas == 1}
